name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: [2.2.108, 3.0.100]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Build with dotnet
      run: dotnet build --configuration Release ./src
    - name: Pack with dotnet
      run: dotnet pack ./src/System.Net.IPNetwork
    - name: Test with dotnet
      run: dotnet test ./src/System.Net.IPNetwork.TestProject.NetCore/System.Net.IPNetwork.TestProject.NetCore.csproj
